name: "Dev Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
# =========================
# Terraform Init + Plan
# =========================
  terraform-plan:
    name: Terraform Init & Plan (DEV)
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: Azure/login@v2
        with:
          client-id: 3d4cb9b2-31d4-4781-8fc7-36392e41968a
          tenant-id: ea9ca8b6-aa2d-4c4a-904a-cb93fd58a0b9
          subscription-id: 86cd11f5-4d26-4e93-bfa9-c0b7b2f44cc9

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: environments/dev

# =========================
# Terraform Apply (DEV)
# =========================
  terraform-apply:
    name: Terraform Apply (DEV)
    runs-on: self-hosted
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: Azure/login@v2
        with:
          client-id: 3d4cb9b2-31d4-4781-8fc7-36392e41968a
          tenant-id: ea9ca8b6-aa2d-4c4a-904a-cb93fd58a0b9
          subscription-id: 86cd11f5-4d26-4e93-bfa9-c0b7b2f44cc9

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Apply
        run: terraform apply -input=false --auto-approve
        working-directory: environments/dev
